In [6]:
#Problem statement 1

In [11]:
import numpy as np

In [8]:
M = int(input("Enter value M : "))
N = int(input("Enter value N : "))
A = int(input("Enter value A : "))

Enter value M : 5
Enter value N : 3
Enter value A : 2


In [9]:
First_Array_Size = M * N

In [10]:
First_Array_Size

15

In [11]:
First_Array = np.arange(First_Array_Size).reshape(M,N)

In [12]:
First_Array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
Second_Array_Size = N * A

In [14]:
Second_Array_Size 

6

In [15]:
Second_Array = np.arange(Second_Array_Size).reshape(N,A)

In [16]:
Second_Array

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
dot_prod = np.dot(First_Array,Second_Array)

In [18]:
dot_prod

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [19]:
#Problem Statement 2


In [35]:
Arr = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5','5'])


In [36]:
np.char.isdigit(Arr)

array([False, False, False, False, False,  True])

In [37]:
np.char.islower(Arr)

array([False, False, False, False,  True, False])

In [38]:
np.char.isupper(Arr)

array([False,  True,  True, False, False, False])

In [1]:
# Problem Statement 3

In [32]:
inp = input("Enter two space seperated values: ")
X,Y = inp.split()
X = int(X)
Y = int(Y)

Enter two space seperated values: 7 9


In [33]:
End = X * 16
End

112

In [34]:
lst1 = list(range(1,End,X))
lst1

[1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]

In [35]:
End_Y = Y * 16
End_Y 

144

In [36]:
lst2 = list(range(1,End_Y,Y))
lst2

[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136]

In [37]:
np1 = np.array(lst1)

In [38]:
type(np1)

numpy.ndarray

In [39]:
np2 = np.array(lst2)

In [40]:
type(np2)

numpy.ndarray

In [41]:
np1 = np1.reshape(4,4)

In [42]:
np1

array([[  1,   8,  15,  22],
       [ 29,  36,  43,  50],
       [ 57,  64,  71,  78],
       [ 85,  92,  99, 106]])

In [43]:
np2 = np2.reshape(4,4)

In [44]:
np2

array([[  1,  10,  19,  28],
       [ 37,  46,  55,  64],
       [ 73,  82,  91, 100],
       [109, 118, 127, 136]])

In [45]:
np3 = np1 - np2
np3

array([[  0,  -2,  -4,  -6],
       [ -8, -10, -12, -14],
       [-16, -18, -20, -22],
       [-24, -26, -28, -30]])

In [46]:
np3 = np3.reshape(16)
np3

array([  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18, -20, -22, -24,
       -26, -28, -30])

In [ ]:
# problem statement 4

In [50]:
lst1 = []

for i in range(0,9):
    x = input("Enter value: ")
    x = int(x)
    lst1.append(x)


Enter value: 23
Enter value: 56
Enter value: 87
Enter value: 3
Enter value: 6
Enter value: 96
Enter value: 4
Enter value: 6
Enter value: 78


In [52]:
np1 = np.array(lst1)

In [53]:
np1

array([23, 56, 87,  3,  6, 96,  4,  6, 78])

In [54]:
lst2 = []

for i in range(0,9):
    x = input("Enter value: ")
    x = int(x)
    lst2.append(x)

Enter value: 12
Enter value: 34
Enter value: 54
Enter value: 7
Enter value: 2
Enter value: 54
Enter value: 6
Enter value: 2
Enter value: 78


In [55]:
np2 = np.array(lst2)

In [56]:
np2

array([12, 34, 54,  7,  2, 54,  6,  2, 78])

In [59]:
np1 = np1.reshape(3,3)
np2 = np2.reshape(3,3)


In [60]:
np3 = np1 - np2

In [61]:
np3

array([[11, 22, 33],
       [-4,  4, 42],
       [-2,  4,  0]])